# Generated by Django 6.0.2 on 2026-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
