# Generated by Django 6.0.2 on 2026-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, upload_to='listing_photos/'),
        ),
    ]
