# Generated by Django 6.0.2 on 2026-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating',
            field=models.CharField(blank=True, choices=[('individual', 'Індивідуальне'), ('central', 'Централізоване'), ('building', 'Будинкове'), ('other', 'Інше')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='pets',
            field=models.CharField(blank=True, choices=[('allowed', 'Можна з тваринами'), ('cats_only', 'Можна з котами'), ('not_allowed', 'Не можна'), ('negotiable', 'По домовленості')], max_length=20),
        ),
    ]
