# Generated by Django 6.0.2 on 2026-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_floor_listing_heating_listing_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=2),
        ),
    ]
