# Generated by Django 6.0.2 on 2026-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_total_floors_alter_listing_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано'), ('archived', 'Архів')], default='published', max_length=20),
        ),
    ]
