# Generated by Django 6.0.2 on 2026-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
