# Generated by Django 6.0.2 on 2026-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_profile_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_avatars/defolticon.png', upload_to='profile_avatars/'),
        ),
    ]
