# Generated by Django 6.0.2 on 2026-02-13 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text="Причина рішення модератора (обов'язково для відхилення)."),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Нова'), ('in_review', 'На розгляді'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listing_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано'), ('archived', 'Архів'), ('blocked', 'Заблоковано')], default='published', max_length=20),
        ),
    ]
